import { Box, Text, Heading } from "@chakra-ui/react";
import { Helmet } from "react-helmet-async";

export default function Terms() {
  return (
    <>
      <Helmet>
        <title>Terms of Service | Relativity AI</title>
        <meta name="description" content="Relativity AI terms of service." />
      </Helmet>
      <Box maxW="720px" mx="auto" py={10}>
        <Heading size="xl" mb={2}>Terms of Service</Heading>
        <Text fontSize="sm" color="fg.muted" mb={8}>Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</Text>

        <Heading size="md" mb={3}>1. Acceptance of Terms</Heading>
        <Text mb={6} lineHeight="tall">
          By accessing or using Relativity AI, you agree to be bound by these terms.
        </Text>

        <Heading size="md" mb={3}>2. Service Description</Heading>
        <Text mb={6} lineHeight="tall">
          Relativity AI is an AI-powered investment research platform that helps users create and run automated analysis agents.
        </Text>

        <Heading size="md" mb={3}>3. User Responsibilities</Heading>
        <Text mb={6} lineHeight="tall">
          You are responsible for maintaining the confidentiality of your account and API keys.
          You are responsible for all activities that occur under your account.
        </Text>

        <Heading size="md" mb={3}>4. Disclaimer</Heading>
        <Text mb={6} lineHeight="tall">
          Relativity AI does not provide financial advice. Analysis results are generated by AI models and should not be
          used as the sole basis for investment decisions. Always conduct your own research and consult qualified professionals.
        </Text>

        <Heading size="md" mb={3}>5. Limitation of Liability</Heading>
        <Text mb={6} lineHeight="tall">
          Relativity AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages
          resulting from your use of the service.
        </Text>

        <Heading size="md" mb={3}>6. Changes to Terms</Heading>
        <Text lineHeight="tall">
          We reserve the right to modify these terms at any time. Continued use of the service after changes constitutes acceptance.
        </Text>
      </Box>
    </>
  );
}
